insert into cube (size) values (1);
insert into cube (size) values (2);
insert into cube (size) values (4);
insert into cube (size) values (1);
insert into cube (size) values (1);
insert into cube (size) values (3);
insert into cube (size) values (2);
insert into cube (size) values (5);
insert into cube (size) values (6);
insert into cube (size) values (2);
insert into torus (r1, r2) values (1, 2);
insert into torus (r1, r2) values (2, 4);
insert into torus (r1, r2) values (4, 5);
insert into torus (r1, r2) values (5, 7);
insert into torus (r1, r2) values (1, 4);
insert into torus (r1, r2) values (2, 2);
insert into torus (r1, r2) values (2, 3);
insert into torus (r1, r2) values (3, 4);
insert into torus (r1, r2) values (6, 1);
insert into torus (r1, r2) values (2, 1);
insert into cuboid (l_size, w_size, d_size) values (1,2,4);
insert into cuboid (l_size, w_size, d_size) values (1,2,5);
insert into cuboid (l_size, w_size, d_size) values (1,2,2);
insert into cuboid (l_size, w_size, d_size) values (2,4,4);
insert into cuboid (l_size, w_size, d_size) values (2,6,8);
insert into cuboid (l_size, w_size, d_size) values (4,4,6);
insert into cuboid (l_size, w_size, d_size) values (5,6,7);
insert into cuboid (l_size, w_size, d_size) values (2,3,4);
insert into cuboid (l_size, w_size, d_size) values (4,4,4);
insert into cuboid (l_size, w_size, d_size) values (1,1,1);
insert into pyramid (size, height) values (1, 2);
insert into pyramid (size, height) values (2, 2);
insert into pyramid (size, height) values (4, 5);
insert into pyramid (size, height) values (3, 4);
insert into pyramid (size, height) values (3, 5);
insert into pyramid (size, height) values (6, 5);
insert into pyramid (size, height) values (4, 2);
insert into pyramid (size, height) values (1, 5);
insert into pyramid (size, height) values (2, 7);
insert into pyramid (size, height) values (1, 2);
insert into sphere (size) values (1);
insert into sphere (size) values (3);
insert into sphere (size) values (4);
insert into sphere (size) values (6);
insert into sphere (size) values (7);
insert into sphere (size) values (3);
insert into sphere (size) values (4);
insert into sphere (size) values (1);
insert into sphere (size) values (7);
insert into sphere (size) values (3);